### ISSUE TITLE
Project directory is not empty (with --force)

### ISSUE THREAD

**Issue by robsontenorio** [laravel/installer#129] opened 2020-09-03 23:45 UTC
- Installer Version: 4.0.0

### Description:

Error trying to create new app, even with `--force`  option

### Steps To Reproduce:
- create a directory `/var/www/app/` and place any file inside it
- cd `/var/www/app/`
- Run `laravel new --dev`
- Also tried `laravel new --force --dev`

```
  [InvalidArgumentException]                        
  Project directory "/var/www/app/." is not empty.
```

*Note 1:* did not pass "app name" because I want app crafted on root folder `/var/ww/app`
*Note 2:* that works on previous version of Laravel Installer

**Comment by peter279k** [comment] 2020-09-04 02:59
Just notice that I have the similar issue when using the `laravel new --dev` on current folder.

Steps To Reproduce:

- All commands are run on Ubuntu 18.04 operating system. And the `laravel/installer` is installed globally.
- Create directory `app` on my home directory.
- Using `cd $HOME/app` to change directory.
- On above directory, running `laravel new --dev` to try to create a new Laravel Application Project.

# Expected

- It should install the application project on above directory.

# Actual

- I get following error message:

```Bash
 _                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|


In NewCommand.php line 153:

  Application already exists!


new [--dev] [--jet] [-f|--force] [--] [<name>]
```

**Comment by driesvints** [comment] 2020-09-08 10:02
Should be fixed I think

**Closed by driesvints** 2020-09-08 10:02 UTC

**Comment by hailwood** [comment] 2020-09-14 07:02
@driesvints it's definitely not fixed in the latest release (v4.0.3)

**Comment by driesvints** [comment] 2020-09-14 08:05
@hailwood can you send a pr?

**Comment by hailwood** [comment] 2020-09-14 08:14
@driesvints I'm happy to, what would you like in the PR?

1. Throw error if "." path and `--force` flag used together
2. Update description of `--force` to "Remove the project directory if it already exists"
3. Rename `--force` to `--delete`

**Comment by cfreear** [comment] 2020-09-14 12:22
From this am I correct in assuming that using `laravel new . --force` to create a new Laravel app in the current directory that may contain other files (.git, .idea etc.) used to work on previous versions of installer it was not a supported use case?

**Comment by driesvints** [comment] 2020-09-14 12:25
Not 100% sure about that.

**Comment by cfreear** [comment] 2020-09-14 12:37
No worries, looks like it's a [wontfix](https://github.com/composer/composer/issues/1135) from composers side anyway. My typical workflow involves opening an empty folder in phpstorm (which creates an .idea folder) and using the built in terminal to run `laravel new`. I'll just have to remember to do it the other way round! 😅

**Comment by hailwood** [comment] 2020-09-14 12:42
You are correct @cfreear.
Thing is that before we were simply [downloading and extracting a zip file](https://github.com/laravel/installer/blob/v3.2.0/src/NewCommand.php#L62-L65) which meant things were quite happy to just extract inplace.

Now we're using [composer create-project](https://github.com/laravel/installer/blob/v4.0.3/src/NewCommand.php#L80) which due to it essentially being a git clone and then deleting the .git directory, doesn't work in a non-empty directory.

Realistically we *could* fix this by using create-project into a tmp directory, and then copying the files over, but I don't believe it's worth the additional complexity it would introduce.

**Comment by driesvints** [comment] 2020-09-14 13:11
@hailwood agreed

**Comment by SiestaCat** [comment] 2023-05-22 05:21
I need to create new project and only .git directory is present. I think this is a bug because .git directory doesn't affects in any way.
